# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f7b68fb7349c624881e62f282356dca908d38ba503752fd475b255bc80604f7344f3c4d1110a45a132679814fa71b0c44fb0fbdb94869b960b5a4ccbc5598eb

test:
  secret_key_base: 2db66d043b3b2089c963fb61fd1606ccf5acbe886e868b101d129f19f5974e8c228215977f6edccc64bc5ba2087ea329f3fd7bd5b54f4d210e356c7dff0095ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
