require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DropinsController do

  # This should return the minimal set of attributes required to create a valid
  # Dropin. As you add validations to Dropin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date" => "2014-05-06 15:28:19" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DropinsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dropins as @dropins" do
      dropin = Dropin.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dropins).should eq([dropin])
    end
  end

  describe "GET show" do
    it "assigns the requested dropin as @dropin" do
      dropin = Dropin.create! valid_attributes
      get :show, {:id => dropin.to_param}, valid_session
      assigns(:dropin).should eq(dropin)
    end
  end

  describe "GET new" do
    it "assigns a new dropin as @dropin" do
      get :new, {}, valid_session
      assigns(:dropin).should be_a_new(Dropin)
    end
  end

  describe "GET edit" do
    it "assigns the requested dropin as @dropin" do
      dropin = Dropin.create! valid_attributes
      get :edit, {:id => dropin.to_param}, valid_session
      assigns(:dropin).should eq(dropin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dropin" do
        expect {
          post :create, {:dropin => valid_attributes}, valid_session
        }.to change(Dropin, :count).by(1)
      end

      it "assigns a newly created dropin as @dropin" do
        post :create, {:dropin => valid_attributes}, valid_session
        assigns(:dropin).should be_a(Dropin)
        assigns(:dropin).should be_persisted
      end

      it "redirects to the created dropin" do
        post :create, {:dropin => valid_attributes}, valid_session
        response.should redirect_to(Dropin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dropin as @dropin" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dropin.any_instance.stub(:save).and_return(false)
        post :create, {:dropin => { "date" => "invalid value" }}, valid_session
        assigns(:dropin).should be_a_new(Dropin)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dropin.any_instance.stub(:save).and_return(false)
        post :create, {:dropin => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dropin" do
        dropin = Dropin.create! valid_attributes
        # Assuming there are no other dropins in the database, this
        # specifies that the Dropin created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dropin.any_instance.should_receive(:update).with({ "date" => "2014-05-06 15:28:19" })
        put :update, {:id => dropin.to_param, :dropin => { "date" => "2014-05-06 15:28:19" }}, valid_session
      end

      it "assigns the requested dropin as @dropin" do
        dropin = Dropin.create! valid_attributes
        put :update, {:id => dropin.to_param, :dropin => valid_attributes}, valid_session
        assigns(:dropin).should eq(dropin)
      end

      it "redirects to the dropin" do
        dropin = Dropin.create! valid_attributes
        put :update, {:id => dropin.to_param, :dropin => valid_attributes}, valid_session
        response.should redirect_to(dropin)
      end
    end

    describe "with invalid params" do
      it "assigns the dropin as @dropin" do
        dropin = Dropin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dropin.any_instance.stub(:save).and_return(false)
        put :update, {:id => dropin.to_param, :dropin => { "date" => "invalid value" }}, valid_session
        assigns(:dropin).should eq(dropin)
      end

      it "re-renders the 'edit' template" do
        dropin = Dropin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dropin.any_instance.stub(:save).and_return(false)
        put :update, {:id => dropin.to_param, :dropin => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dropin" do
      dropin = Dropin.create! valid_attributes
      expect {
        delete :destroy, {:id => dropin.to_param}, valid_session
      }.to change(Dropin, :count).by(-1)
    end

    it "redirects to the dropins list" do
      dropin = Dropin.create! valid_attributes
      delete :destroy, {:id => dropin.to_param}, valid_session
      response.should redirect_to(dropins_url)
    end
  end

end
